<a href="https://colab.research.google.com/github/kunkunmaru/data-analysis-basic-kadai/blob/main/kadai_003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

a = ([0,1],[2,3],[4,5])
b = ([0,1,2,3],[4,5,6,7])
print(np.dot(a,b))

print(np.dot(a,b).max())

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
